apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage_sample_java
  description: Backstage Sample Java Project
  tags:
    - java
spec:
  type: service
  lifecycle: production
  owner: user:guest
  system: note-app
  dependsOn: ['resource:note-db']