apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: notes-service
  description: Backstage Sample Java Project (Notes-Service)
  tags:
    - notes-service
    - java
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: production
  owner: user:guest
  system: notes-app
  dependsOn:
    - 'Resource:notes-db'
  providesApis:
    - notes-service-api