apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: notes-db
  description: Stores Notes
spec:
  type: database
  owner: user:guest
  dependencyOf:
    - 'Component:notes-service'
  system: notes-app