server:
  port: 8080

spring:
  application:
    name: backstage_sample_java
  r2dbc:
    url: r2dbc:mysql://localhost:3306/notedb?characterEncoding=utf8
    username: admin
    password: admin
  flyway:
    enabled: true
    url: jdbc:mysql://localhost:3306/notedb?characterEncoding=utf8
    user: admin
    password: admin
    driver: com.mysql.jdbc.Driver
    baseline-on-migrate: true
    locations: classpath:db/migration

springdoc:
  show-actuator: true
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html